<?php
/**
 * Custom Footer Content Block
 *
 * This section renders the custom footer content for the website, including copyright and contact information. It encourages users to reach out for customization and feedback via email.
 *
 * @author Developers-Alliance team
 * @Copyright (c) 2024 Developers-alliance (https:// www. developers-alliance. com)
 * @website https://developers-alliance.com
 * @package Devall_CustomerFeedback
 * @version 1.0.0
 */
?>
<div class="custom-footer-content">
    Developers Alliance (c). For customization and feedback please reach out to
    <a href="mailto:hello@developers-alliance.com">hello@developers-alliance.com</a>
</div>
